### ISSUE TITLE
Getting Token however my CORS api denies with 401

### ISSUE THREAD

**Issue by msms007** [krzyhook/angular-adal-example#1]
Thank you so much for a nice sample.. Really appreciate that. However, I am having issue with connecting to my application api. which runs on a different domain thought. getting 401 authorization denied. My old angular JS application can consume the same end point without any issues. (its using angular-adal.js 1.0.13).

Any clues or thoughts on this?.

**Comment by kkoziarski** [comment]
Hi,
Are you able to get token from Azure?
If you are getting auth token from Azure then it may be your backend api app which is incorrectly configured.
Is your backend api app written in .net? 
Take a look at my [Startup.cs](https://github.com/krzyhook/angular-adal-example/blob/master/Backend.DotNetCore/src/Startup.cs) where you need to correctly configure JwtBearerOptions by setting `Audience` and `Authority`.

If your app runs on a different domain, you need to allow CORS:
```
app.UseCors(builder =>
	builder.AllowAnyOrigin()
		.AllowAnyHeader()
		.AllowAnyMethod()
);
```

**Comment by msms007** [comment]
Thanks for the guidance. appreciate your help in this regard. I was able to access api after I remove roles check in the [Authorize] Attribute of the WebApi. Looks like the token claims is missing roles. I will explore further on that.. Thank you so much for the example. it is really helpful.
